DROP TABLE RUBBISH;
DROP TABLE USER;
DROP TABLE GROUP_;


CREATE TABLE GROUP_
(
    GRP_ID BIGINT PRIMARY KEY NOT NULL,
    GRP_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE USER_
(
    USR_ID BIGINT PRIMARY KEY NOT NULL,
    USR_NAME VARCHAR(255) NOT NULL,
    GRP_ID BIGINT NOT NULL,
    FOREIGN KEY (GRP_ID) REFERENCES GROUP_(GRP_ID)
);


CREATE TABLE RUBBISH
(
	RBH_ID BIGINT PRIMARY KEY NOT NULL,
	RBH_WEIGHT INT NOT NULL,
	RBH_NB_USER INT NOT NULL,
	RBH_DATE TIMESTAMP NOT NULL,
	USR_ID BIGINT NOT NULL,
	FOREIGN KEY (USR_ID) REFERENCES USER_(USR_ID)
);

CREATE SEQUENCE seq_rubbish_user_usr_id START 1;
CREATE SEQUENCE seq_rubbish_rubbish_rbh_id START 1;
CREATE SEQUENCE seq_rubbish_group_grp_id START 1;


INSERT INTO GROUP_ (GRP_ID, GRP_NAME) VALUES (nextval('seq_rubbish_group_grp_id'),'Les pintates');

INSERT INTO USER_ (USR_ID, USR_NAME, GRP_ID) VALUES (nextval('seq_rubbish_user_usr_id'),'Papinou & Maminou',1);
INSERT INTO USER_ (USR_ID, USR_NAME, GRP_ID) VALUES (nextval('seq_rubbish_user_usr_id'),'Mélodie',1);
INSERT INTO USER_ (USR_ID, USR_NAME, GRP_ID) VALUES (nextval('seq_rubbish_user_usr_id'),'Julie',1);
INSERT INTO USER_ (USR_ID, USR_NAME, GRP_ID) VALUES (nextval('seq_rubbish_user_usr_id'),'Coralie',1);
INSERT INTO USER_ (USR_ID, USR_NAME, GRP_ID) VALUES (nextval('seq_rubbish_user_usr_id'),'Maëva',1);


ALTER TABLE USER_ ADD COLUMN USR_EMAIL VARCHAR(512) NOT NULL DEFAULT 'x';
ALTER TABLE USER_ ADD COLUMN USR_PASSWORD VARCHAR(512) DEFAULT 'x';

update USER_ set USR_EMAIL = 'eric.pelieu@gmail.com', USR_PASSWORD='123' where usr_id = 2;

ALTER TABLE USER_ ADD COLUMN USR_UUID_REGISTER VARCHAR(512) NULL;

ALTER TABLE USER_ ADD COLUMN USR_ACTION_DATE TIMESTAMP NULL;

ALTER TABLE USER_ ADD COLUMN USR_STATE INT NOT NULL DEFAULT 0;

ALTER TABLE USER_ ALTER USR_NAME DROP NOT NULL;
ALTER TABLE USER_ ALTER GRP_ID DROP NOT NULL;
ALTER TABLE USER_ ALTER USR_PASSWORD DROP NOT NULL;



CREATE TABLE RUBBISH_TYPE
(
    RUT_ID BIGINT PRIMARY KEY NOT NULL,
    RUT_LABEL VARCHAR(255) NOT NULL
);


CREATE SEQUENCE seq_rubbish_rubbish_type_rut_id START 1;

INSERT INTO rubbish_type(RUT_ID, RUT_LABEL) VALUES (1,'Cuisine');
INSERT INTO rubbish_type(RUT_ID, RUT_LABEL) VALUES (2,'Salle de bain');
INSERT INTO rubbish_type(RUT_ID, RUT_LABEL) VALUES (3,'Tri sélectif');
INSERT INTO rubbish_type(RUT_ID, RUT_LABEL) VALUES (4,'Verre');
INSERT INTO rubbish_type(RUT_ID, RUT_LABEL) VALUES (5,'Bureau');
INSERT INTO rubbish_type(RUT_ID, RUT_LABEL) VALUES (6,'Chambre');
INSERT INTO rubbish_type(RUT_ID, RUT_LABEL) VALUES (7,'Autre');


ALTER TABLE RUBBISH ADD COLUMN RUT_ID BIGINT NOT NULL 

ALTER TABLE RUBBISH 
ADD CONSTRAINT FK_RUBBISH_RUBBISH_TYPE
FOREIGN KEY (RUT_ID) 
REFERENCES RUBBISH_TYPE(RUT_ID);
   


CREATE SEQUENCE seq_rubbish_user_group_ugp_id START 1;


CREATE TABLE USER_GROUP
(
	UGP_ID BIGINT NOT NULL,
    USR_ID BIGINT NOT NULL,
    GRP_ID BIGINT NOT NULL,
    UGP_STATE VARCHAR(64) NOT NULL,
    UGP_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY(UGP_ID),
    FOREIGN KEY (USR_ID) REFERENCES USER_(USR_ID),
    FOREIGN KEY (GRP_ID) REFERENCES GROUP_(GRP_ID)
);















